manga/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :borrows
  root to: 'pages#home'

  devise_for :users

  resources :users do
    member do
      post :del1
      post :del2
      post :del3
    end
  end

  resources :ouvrages do
    resources :commentaries do
      member do
        put "like", to: "commentaries#upvote"
        put "dislike", to: "commentaries#downvote"
      end
    end
    member do
      post :borrows
    end
  end
   
  resources :users, :only => [:show]
  
  get 'liste' => 'users#liste'

  get 'search' => 'ouvrages#search'

  get 'user_edit' => "users#edit"

end

manga/app/models/ouvrage.rb
class Ouvrage < ActiveRecord::Base
  ratyrate_rateable "note"

  has_many :commentaries
  
  def self.search(search)
  	if search
  		where("title LIKE ? OR genre LIKE ? OR author LIKE ? OR editor LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%")
  	end
  end
end

manga/app/controllers/ouvrages_controller.rb
class OuvragesController < ApplicationController

  def index
    manga_per_page = 5

    sort = case params['sort']
           when "title"  then "title"
           when "author"   then "author"
           when "editor" then "editor"
           when "date" then "release_date"
           when "genre" then "genre"
           when "title_reverse"  then "title DESC"
           when "author_reverse"   then "author DESC"
           when "editor_reverse" then "editor DESC"
           when "date_reverse" then "release_date DESC"
           when "genre_reverse" then "genre DESC"
           end

    if params[:search]
      @ouvrages = Ouvrage.paginate(:page => params[:page], :per_page => manga_per_page).order(sort).search(params[:search])
    else
      @ouvrages = Ouvrage.paginate(:page => params[:page], :per_page => manga_per_page).order(sort)
    end
  end

  def show
    @ouvrage = Ouvrage.find(params[:id])
    @comments = Commentary.where(:ouvrage_id => @ouvrage.id).paginate(:page => params[:page], :per_page => 5).order("created_at DESC")
    @missing = @ouvrage.missing_tome.split(";")
    @tab = []
    if @missing != "-"
      for n in (@ouvrage.begin..@ouvrage.final) do
        @missing.each do |tome|
          if tome.to_i == n
            @tab[n] = false
          else
            @tab[n] = true
          end
        end
      end
    end
    if user_signed_in?
      @user = current_user
    end
  end

  def borrows
    @ouvrage = Ouvrage.find(params[:id])

    @user = current_user
    @emprunt = @ouvrage.title+" tome "+params[:tome].to_s
    @test1 = User.where(borrow1: @emprunt)
    @test2 = User.where(borrow2: @emprunt)
    @test3 = User.where(borrow3: @emprunt)

    if @test1 == [] && @test2 == [] && @test3 == [] && @user.current_borrows < 3
      @user.update_attribute(:current_borrows, @user.current_borrows + 1)
      if @user.borrow1 == ""
        @user.update_attribute(:borrow1, @emprunt)
      elsif @user.borrow2 == ""
        @user.update_attribute(:borrow2, @emprunt)
      elsif @user.borrow3 == ""
        @user.update_attribute(:borrow3, @emprunt)
      end
      redirect_to :back, notice: "Manga Emprunté"
    else
      if @user.current_borrows == 3
        redirect_to :back, notice: "Limite d'emprunts atteint"
      else
        redirect_to :back, notice: "Manga indisponible"
      end
    end
  end

end

manga/app/helpers/ouvrages_helper.rb
module OuvragesHelper

  def sort_link_helper(text, param)
    key = param
    key += "_reverse" if params[:sort] == param
    options = {
      :url => {:action => 'index', :params => params.merge({:sort => key, :page => nil})},
      :update => 'table',
      :before => "Element.show('spinner')",
      :success => "Element.hide('spinner')"
    }
    html_options = {
      :title => "Trier selon ce champ",
      :href => url_for(:action => 'index', :params => params.merge({:sort => key, :page => nil}))
    }
    link_to(text, options, html_options)
  end

end

manga/app/views/ouvrages/index.html.haml
.row
	.col-xs-9-

		%h2
			Recherche

		= form_tag ouvrages_path, :method => 'get' do
			%p
				= text_field_tag :search, params[:search]
				= submit_tag "Search", :name => nil

		%h2 Bibliothèque

		%table.table.cadre
			%thead

				%td
					Couverture
				%td
					= sort_link_helper "Titre", "title"
				%td
					= sort_link_helper "Auteur", "author"
				%td
					= sort_link_helper "Editeur", "editor"
				%td
					= sort_link_helper "Date", "date"
				%td
					= sort_link_helper "Genre", "genre"
				%td
					Synopsis
				%td
					Lien

			%tbody
				- @ouvrages.each do |ouvrage|
					%tr
						%td
							= image_tag "/#{ouvrage.title}.jpg", alt: "Couverture", :width => "auto", :height => "100"
						%td
							= ouvrage.title
						%td
							= ouvrage.author
						%td
							= ouvrage.editor
						%td
							= ouvrage.release_date
						%td 
							= ouvrage.genre
						%td
							= ouvrage.synopsis[0..199] +"..."
						%td
							%a{:href => "/ouvrages/#{ouvrage.id}"}
								.black Voir le manga
			= will_paginate @ouvrages

manga/app/views/ouvrages/show.html.haml
.row

	.col-md-4
		.img-thumbnail= image_tag "/#{@ouvrage.title}.jpg", alt: "Couverture", :width => "275", :height => "auto"

	.col-md-4
		.description-bloc.cadre
			.li
				%u Titre: 
				= @ouvrage.title
			.li
				%u Auteur:
				= @ouvrage.author
			.li
				%u Editeur:
				= @ouvrage.editor
			.li
				%u Date de Publication:
				= @ouvrage.release_date
			.li
				%u Genre(s):
				= @ouvrage.genre
			-if user_signed_in?
				.li
					%u Tome(s) Disponible(s):
					.li
						- for n in (@ouvrage.begin..@ouvrage.final) do
							-if @missing == "-"
								= link_to n, borrows_ouvrage_path(@ouvrage, tome: n), method: :post
							-else
								-if @tab[n] == true
									= link_to n, borrows_ouvrage_path(@ouvrage, tome: n), method: :post
					%u.li NB Emprunt:
					=@user.current_borrows

			- else
				.li
					%u Tome(s) Disponible(s):
					.li
						- for n in (@ouvrage.begin..@ouvrage.final) do
							-if @missing == "-"
								= n
							-else
								-if @tab[n] == true
									= n
			.li
				= rating_for @ouvrage, 'note', disable_after_rate: true,enable_half: true, half_show: true, cancel: true



.cadre
	%h3
		Synopsis
	%p
		= @ouvrage.synopsis

-if user_signed_in?
	%h3
		Nouveau Commentaire
	%p
		= form_for [@ouvrage, Commentary.new] do |f|
			= f.text_area :texte, size: "60x15"
			= f.submit "Publier"

%h3
	Commentaires
%table.table.cadre
	%thead
		%td
			Pseudo
		%td
			Texte
	%tbody
		- @comments.each do |comment|
			%tr
				%td
					- if User.find(comment.user_id).pseudo == nil
						Utilisateur Anonyme
					- else
						= User.find(comment.user_id).pseudo
				%td
					.col-md-8
						= comment.texte
=will_paginate @comments