manga/config/routes.rb
Rails.application.routes.draw do

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :borrows
  root to: 'pages#home'

  devise_for :users

  resources :users do
    member do
      post :del1
      post :del2
      post :del3
    end
  end

  resources :ouvrages do
    resources :commentaries do
      member do
        put "like", to: "commentaries#upvote"
        put "dislike", to: "commentaries#downvote"
      end
    end
    member do
      post :borrows
    end
  end
   
  resources :users, :only => [:show]
  
  get 'liste' => 'users#liste'

  get 'search' => 'ouvrages#search'

  get 'user_edit' => "users#edit"

end

manga/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :commentaries
  ratyrate_rater
end

manga/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def del1
		@user = current_user
		@user.update_attribute(:borrow1, "")
		@user.update_attribute(:current_borrows, @user.current_borrows - 1)
		redirect_to :back
	end

	def del2
		@user = current_user
		@user.update_attribute(:borrow2, "")
		@user.update_attribute(:current_borrows, @user.current_borrows - 1)
		redirect_to :back
	end

	def del3
		@user = current_user
		@user.update_attribute(:borrow3, "")
		@user.update_attribute(:current_borrows, @user.current_borrows - 1)
		redirect_to :back
	end

	def liste
		user_per_page = 5

		sort = case params['sort']
			when "email" then "email"
			when "pseudo" then "pseudo"
			when "name" then "name"
			when "surname" then "surname"
			when "course" then "course"
			when "year" then "year"
			when "current_borrows" then "current_borrows"
			when "last_sign_in_at" then "last_sign_in_at"
			when "admin" then "admin"
			when "email_reverse" then "email DESC"
			when "pseudo_reverse" then "pseudo DESC"
			when "name_reverse" then "name DESC"
			when "surname_reverse" then "surname DESC"
			when "course_reverse" then "course DESC"
			when "year_reverse" then "year DESC"
			when "current_borrows_reverse" then "current_borrows DESC"
			when "last_sign_in_at_reverse" then "last_sign_in_at DESC"
			when "admin_reverse" then "admin DESC"
			end

		@users = User.paginate(:page => params[:page], :per_page => user_per_page).order(sort)
	end

	def update
		@user = current_user
		if @user.update(user_params)
			redirect_to '/'
		else
			render 'user_edit'
		end
	end
	
	private

	def user_params
		params.require(:user).permit(:name,:surname,:pseudo,:course,:year)
	end	

end

manga/app/helpers/user_helper.rb
module UserHelper
end

manga/app/helpers/users_helper.rb
module UsersHelper
	def sort_link_helper_list(text, param)
    key = param
    key += "_reverse" if params[:sort] == param
    options = {
      :url => {:action => 'liste', :params => params.merge({:sort => key, :page => nil})},
      :update => 'table',
      :before => "Element.show('spinner')",
      :success => "Element.hide('spinner')"
    }
    html_options = {
      :title => "Trier selon ce champ",
      :href => url_for(:action => 'liste', :params => params.merge({:sort => key, :page => nil}))
    }
    link_to(text, options, html_options)
  end
end

manga/app/views/users/edit.html.haml
.cadre

	%h3
		Mettre à jour vos données

	= form_for current_user, method: :put do |f|
		.field
			= f.label "Prénom"
			= f.text_field :name
		.field
			= f.label "Nom"
			= f.text_field :surname
		.field
			= f.label "Pseudo"
			= f.text_field :pseudo
		.field
			= f.label "Filière"
			= f.text_field :course
		.field
			= f.label "Promotion"
			= f.text_field :year
		.actions
			= f.submit "Confirmer"

manga/app/views/users/liste.html.haml
-if current_user.try(:admin?)

	.row
		.col-xs-9-
			.panel-title
				.h2 Liste d'inscrits

		
		%table.table.cadre
			%thead

				%td
					= sort_link_helper_list "Email", "email"
				%td
					= sort_link_helper_list "Pseudo", "pseudo"
				%td
					= sort_link_helper_list "Nom", "surname"
				%td
					= sort_link_helper_list "Prénom", "name"
				%td
					= sort_link_helper_list "Emprunts", "current_borrows"
				%td
					= sort_link_helper_list "Filière", "course"
				%td
					= sort_link_helper_list "Promotion", "year"
				%td
					= sort_link_helper_list "Admin?", "admin"
				%td
					= sort_link_helper_list "Dernière Connexion", "last_sign_in_at"


			%tbody
				- @users.each do|user|
					%tr
						%td
							= user.email
						%td
							= user.pseudo
						%td
							= user.surname
						%td
							= user.name
						%td
							- if user.borrow1 != ""
								.li
									= user.borrow1
							- if user.borrow2 != ""
								.li
									= user.borrow2
							- if user.borrow3 != ""
								.li
									= user.borrow3
						%td
							= user.course
						%td
							= user.year
						%td
							- if user.try(:admin?)
								Oui
							- else
								Non
						%td
							=user.last_sign_in_at

manga/app/views/users/show.html.haml
.row.cadre
	.col-md-4
		.decription-bloc.p
			.li
				%u Email:
				= current_user.email
			.li
				%u Number of Borrows:
				= current_user.current_borrows
			.li
				%u Emprunt 1:
				- if current_user.borrow1 != ""
					- n = 1
					= link_to current_user.borrow1, del1_user_path(), method: :post
			.li
				%u Emprunt 2:
				- if current_user.borrow2 != ""
					- n = 2
					= link_to current_user.borrow2, del2_user_path(), method: :post
			.li
				%u Emprunt 3:
				- if current_user.borrow3 != ""
					- n = 3
					= link_to current_user.borrow3, del3_user_path(), method: :post
			.li
				%u Pseudonyme:
				= current_user.pseudo
			.li
				= link_to "Changer de mot de passe", edit_user_registration_path
			.li
				= link_to "Modifier vos données", user_edit_path